repos:
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: black
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [python, pyi]

      - id: pytest-check
        verbose: true
        name: pytest-check
        entry: python -m pytest tests/ -x
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.0
    hooks:
      - id: absolufy-imports
        files: ^adsimulo/

  - repo: https://github.com/codespell-project/codespell
    rev: v2.0.0
    hooks:
      - id: codespell
        types_or: [python, rst, markdown]
        files: ^(adsimulo|docs)/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: \.txt$
      - id: trailing-whitespace
      - id: detect-private-key
      - id: check-case-conflict
      - id: check-merge-conflict

  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ['--max-line-length=88']
        additional_dependencies:
            - flake8-blind-except
            - flake8-bugbear
            - flake8-comprehensions
            - flake8-implicit-str-concat
            - flake8-simplify
